### ISSUE TITLE
add Mutant Year Zero

### ISSUE THREAD

**Issue by 9littlebees** [stevesea/Adventuresmith#173]
This Swedish gritty post-apocalyptic superhero survival game was released in English in 2014 and won the 2015 Silver Ennie for Best Rules. There is an expansion called GenLab Alpha which expands on the rules by adding a new playable "race" of anthropomorphic animals, and there are 2 further expansions coming, "Mechatron" with playable robots (2017) and "Elysium" with unmutated humans (2018/19).

Anyway, the tables from the core book that would work well with Adventuresmith are:

*mutation misfires (p69)
*mutations list (p71 - would be good to add the 4 additional mutations from GenLab Alpha) 
*critical injuries (p91)
*NPC zone expeditions (p124)
*random events in the ark (p137)
*random events in the zone (p137)
*random threats against the ark (p146)
*zone sector creation (lots of separate tables that can be combined for zone creation on pp156-161, but the "threats in the zone" tables would be great as a standalone geverator in addition)
*artifact table (p189) 
*scrap table (pp262-264)

**Comment by stevesea** [comment]
some more discussion here: https://plus.google.com/+MattKay/posts/FuQvF2uKrhX

**Comment by stevesea** [comment]
Matt, took a quick glance at the GenLab Alpha book... what additional 4 mutations? Haven't found them

**Comment by 9littlebees** [comment]
Oh right, they were added to the optional card deck that came with a
physical book. I can look up the text for two of them (they're in another
supplement), and I'll take some pics of the other two and email the whole
lot across.

There are also some tables from GLA that would be cool to add, but I'll add
that to another content request.

**Comment by stevesea** [comment]
closing this as done, will be part of next release. gh-182 logged to finish up the 'push' rolls
