### ISSUE TITLE
adventuresmith-cli raise erro on perillious wild on discovery

### ISSUE THREAD

**Issue by dynamikdev** [stevesea/Adventuresmith#181]
Hi , there is an error on use of adventure-cli for the discovery Preilious wild file (also with the last one cli)
way to reproduce : 
extract cli from zip file 
clone repo
and do this
> ./adventuresmith-cli/bin/adventuresmith-cli run <pathToTheRepo>/Adventuresmith/adventuresmith-core/src/main/resources/org/stevesea/adventuresmith/core/perilous_wilds/discovery.yml 
> ERROR problem running generator discovery.yml: conflicting context key: details

**Comment by stevesea** [comment]
Thanks! I'll take a look!

**Comment by stevesea** [comment]
seems like it's only for generators run from file-system. still investigating

**Comment by stevesea** [comment]
fixed w/ changes in hash db52a2edc32b97ad64ea509bcfd9aa0cf10d320a . cleaned up a bunch of the data loading and squashed some duplicated logic in file-loading/resource-loading.

**Comment by stevesea** [comment]
will be releasing a new drop in a couple days that'll include the changes
