### ISSUE TITLE
Any plans to port this to the AppStore

### ISSUE THREAD

**Issue by bbuck** [stevesea/Adventuresmith#210]
Do you have any plans now, or in the future to port this to iOS? I could help out a port if one doesn't exist yet.

Or are you aware of similar apps on iOS?

**Comment by stevesea** [comment]
I've just barely started working on a new version using [Flutter]( https://flutter.io/). With that, I can release to both iOS and Android.

But, I have no ETA on when it'll be done.

**Comment by bbuck** [comment]
Cool, well that answers my question so I suppose I'll close this issue. And look forward to it when you finish it!

Thanks for the work on this, awesome tool.

**Comment by stevesea** [comment]
Thanks! I'm glad you're enjoying the app. 

As I get closer with the iOS version, I'll announce it on the [G+ community](https://plus.google.com/communities/101389134352217517231) and other places.
