### ISSUE TITLE
Adventuresmith-cli raising error

### ISSUE THREAD

**Issue by TKPereiraEscriba** [stevesea/Adventuresmith#221]
Hi there. I've identified some issues. 

First: latest release (**0.29.4**) doesn't contain "Adventuresmith-cli" zip file. Release **0.29.3** does have it, but itsn't working (see below).

Second: on release **0.29.3**, when executing example command from wiki (see below)...

Example command: 
> .\adventuresmith-cli\bin\adventuresmith-cli run .\adventuresmith-cli\examples\spells.yml -i 5

... it gives the error below:

> ERROR problem running generator spells.yml: Unable to find files matching 'C:\Te
ste\as-cli-0293\bin\wizard_names'. Tried: [C:\Teste\as-cli-0293\bin\wizard_names
.en_US.yml, C:\Teste\as-cli-0293\bin\wizard_names.en.yml, C:\Teste\as-cli-0293\b
in\wizard_names.pt_BR.yml, C:\Teste\as-cli-0293\bin\wizard_names.pt.yml, C:\Test
e\as-cli-0293\bin\wizard_names.yml

It seems the "Adventuresmith-cli" is expecting all the others reference *.YML files to be in the same folder (\bin) as the .BAT file 

Release **0.27.8** has the same issue. 

Release **0.26.0** has a different issue: it searches in the right folder (\examples), but does not find .META.YML files. In fact, they don't exist in here or on the two releases above.

See error:

> C:\Teste\as-cli-0260\bin>adventuresmith-cli run %P%\examples\spells.yml -i 5
ERROR problem running generator spells.yml: Unable to find files matching 'C:\Te
ste\as-cli-0260\examples\spells.meta'. Tried: [C:\Teste\as-cli-0260\examples\spe
lls.meta.en_US.yml, C:\Teste\as-cli-0260\examples\spells.meta.en.yml, C:\Teste\a
s-cli-0260\examples\spells.meta.pt_BR.yml, C:\Teste\as-cli-0260\examples\spells.
meta.pt.yml, C:\Teste\as-cli-0260\examples\spells.meta.yml]

I suppose the .META.YML files are not needed anymore, althoug they existed on release **0.24.2**, which is **the only release where "Adventuresmith-cli" runs the command example from Wiki whithout errors**.

So... am I to use that release?

Regards,
T. K. Pereira

P.S: I'm from Brazil, so forgive my poor english.

**Comment by stevesea** [comment]
your english is excellent! thank you for raising the issue, and being so thorough. I'll take a look.

It likely has the same issue, but I've uploaded the adventuresmith-cli for the latest release here: https://github.com/stevesea/Adventuresmith/releases/tag/0.30.0

**Comment by TKPereiraEscriba** [comment]
Hi, Steve. Indeed, the issue persists. I've just tried it out. Not working. I'll await news from you.

Thanks.
T. K. Pereira

**Comment by stevesea** [comment]
I don't have a Windows system to test it out on, but I believe this version will fix the issues you found: https://github.com/stevesea/Adventuresmith/releases/tag/0.30.2

There were a couple problems:
* I'd removed those .meta.yml files from the examples -- I've restored those 
* I also print out a warning if the *.meta.yml files can't be found now, instead of exiting.
* when locating a file to import (say the wizard_names import from the spells.yml in the example), the code was only checking for "/" instead platform-independent directory separators.

**Comment by TKPereiraEscriba** [comment]
Hi there, Steve. Just tried out release 0.30.2 and it seems to be working fine now.

Could I suggest an extra argument to the RUN command? When trying the "Overly Simple Example" (random male and female names), I got several warning messages (see below) about absent .META files, like expected in this simple example, I suppose.

> C:\AdvSmi\as-cli-0302\bin>adventuresmith-cli run %P%\meus\testeSimples.yml -i 5
> 
> WARN  unable to locate metadata for testeSimples.yml: Unable to find files match
> ing 'C:\AdvSmi\as-cli-0302\meus\testeSimples.meta'. Tried: [C:\AdvSmi\as-cli-030
> 2\meus\testeSimples.meta.en_US.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta
> .en.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta.pt_BR.yml, C:\AdvSmi\as-cl
> i-0302\meus\testeSimples.meta.pt.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.me
> ta.yml]
> WARN  unable to locate metadata for testeSimples.yml: Unable to find files match
> ing 'C:\AdvSmi\as-cli-0302\meus\testeSimples.meta'. Tried: [C:\AdvSmi\as-cli-030
> 2\meus\testeSimples.meta.en_US.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta
> .en.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta.pt_BR.yml, C:\AdvSmi\as-cl
> i-0302\meus\testeSimples.meta.pt.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.me
> ta.yml]
> WARN  unable to locate metadata for testeSimples.yml: Unable to find files match
> ing 'C:\AdvSmi\as-cli-0302\meus\testeSimples.meta'. Tried: [C:\AdvSmi\as-cli-030
> 2\meus\testeSimples.meta.en_US.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta
> .en.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta.pt_BR.yml, C:\AdvSmi\as-cl
> i-0302\meus\testeSimples.meta.pt.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.me
> ta.yml]
> WARN  unable to locate metadata for testeSimples.yml: Unable to find files match
> ing 'C:\AdvSmi\as-cli-0302\meus\testeSimples.meta'. Tried: [C:\AdvSmi\as-cli-030
> 2\meus\testeSimples.meta.en_US.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta
> .en.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta.pt_BR.yml, C:\AdvSmi\as-cl
> i-0302\meus\testeSimples.meta.pt.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.me
> ta.yml]
> WARN  unable to locate metadata for testeSimples.yml: Unable to find files match
> ing 'C:\AdvSmi\as-cli-0302\meus\testeSimples.meta'. Tried: [C:\AdvSmi\as-cli-030
> 2\meus\testeSimples.meta.en_US.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta
> .en.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.meta.pt_BR.yml, C:\AdvSmi\as-cl
> i-0302\meus\testeSimples.meta.pt.yml, C:\AdvSmi\as-cli-0302\meus\testeSimples.me
> ta.yml]
> 
> INFO  Running generator: C:\AdvSmi\as-cli-0302\meus\testeSimples.yml
> Margaret
> Bob
> Roger
> Bob
> Sally

Wouldn't be better if we could suppress warning messages (by use of an extra RUN command argument) so that we can make tests on a cleaner environment?

Just a suggestion. 

Thanks for your attention. Now I'm off to play with custom generators. See ya soon.

T. K. Pereira

**Comment by stevesea** [comment]
This version should suppress those warning messages: https://github.com/stevesea/Adventuresmith/releases/tag/0.30.3
