### ISSUE TITLE
BUG: augmented_reality/backup.yml is calling wrong template

### ISSUE THREAD

**Issue by TalonK** [stevesea/Adventuresmith#222]
I noticed this bug as a new user of your app and signed up to report it.  When you select the Augmented Reality/Corps & Cops "Call for back up" option it gives you the same results as if you selected the "Response Level" button.  A quick look thru the core libraries indicated why.  This is the current code in backup.yml:

---
imports:
- armed_response

templates:
- "{{armed_response.response_level}}"

Looking in armed_response.yml the correct template to call would be armed_response.back_up instead.

**Comment by stevesea** [comment]
Thank you! I'll get that fixed up right away

**Comment by stevesea** [comment]
will be corrected in next release

**Comment by stevesea** [comment]
0.30.4 release pushed to main release channel now
