### ISSUE TITLE
Queen's Cavalier "Fresh" Random Backstory Glitch

### ISSUE THREAD

**Issue by WanderingAutumn** [stevesea/Adventuresmith#223]
This doesn't happen every time you generate a result, but I noticed that when the Queen's Cavalier random backstory is set to "Fresh", it occasionally brings up an error message instead. Some screenshots:

![Part 1](https://user-images.githubusercontent.com/70624165/91937293-98854180-ecbf-11ea-8dbd-ab77a951ac52.png)
![Part 2](https://user-images.githubusercontent.com/70624165/91937301-9cb15f00-ecbf-11ea-87a5-5ee27ca41bf6.png)

So far, this is the only error/Glitch I've encountered, and I've been using the Android app for a while now. (Love it, by the way!)

**Comment by stevesea** [comment]
thank you for reporting the problem! should be fixed in the next release
