### ISSUE TITLE
Queen's Cavalier Tables Does not work

### ISSUE THREAD

**Issue by emrergin** [stevesea/Adventuresmith#228]
On my device, Queen's Cavalier Tables, all of them are unresponsive. And they are the only ones so.

**Comment by stevesea** [comment]
Can you provide more detail:
* which version of Adventuresmith?
* which device and version of Android are you using?

**Comment by stevesea** [comment]
'unresponsive' as in the buttons do nothing? Do the buttons themselves animate when clicked? Does the application crash?

Or, does it appear similar to other screens, and it's just that no results appear?

**Comment by stevesea** [comment]
Actually, I _think_ I tracked down the problem -- one of the differences with the QC generators is there's an English version, but not a default version. If you're using a non-English locale, things probably error out in a way I hadn't expected to need to handle.

**Comment by emrergin** [comment]
I am sorry that I missed your replies to this.

I tried to change my locale and yes, it solves the issue for the current release on Google Play.

However, on the release candidate here, I get a crash even before reaching the main screen.

Thanks!

**Comment by stevesea** [comment]
yep, there's a problem with the release build resulting in the crash (debug build works ok). Still need to fix the build
