### ISSUE TITLE
Add modern generators

### ISSUE THREAD

**Issue by phrakture** [stevesea/Adventuresmith#67]
I don't know where to source this, but modern npcs and locations would be wonderful

**Comment by stevesea** [comment]
'modern' as in present-day (20th/21st century)? 

Any particular setting, or flavors, in addition to the time period? Horror, supernatural, super-hero, etc?

Any examples of what you have in mind on Abulafia  http://www.random-generator.com/index.php?title=Main_Page  or other generator sites would be handy

**Comment by phrakture** [comment]
I'm currently playing Urban Shadows, so "urban fantasy" would be my go-to

**Comment by phrakture** [comment]
Heh, I saw your ask in his G+ thread. That's exciting.

**Comment by stevesea** [comment]
I'm leaning towards closing this ticket -- the Roll XX and Augmented Reality generators added a bunch of non-fantasy stuff. Any objections?
